# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 17:45
from __future__ import unicode_literals

from django.db import migrations
import os

def insert_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    
    Site.objects.create(
        domain= os.getenv('DJANGO_SITE', 'google.com'),
        name= os.getenv('DJANGO_SITE', 'google.com')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_site)
    ]
