# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_office365', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 1, 18, 40, 463556, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
