# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_office365', '0002_victim_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
